### This template is meant to be used by a multi-language repo running RichNav.
### It provides rich navigation for C#, JavaScript, TypeScript, C++, and Java
### Please fill anything marked above with a "# **** #" comment with the value appropriate for your repository

name: Rich Code Navigation

on:
  pull_request:
  push:
  # **** Add any the name of your default branch, or any branch you want indexed on every push **** #
    branches: [ main ]

jobs:
  richnav:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    # **** If you've defined a specific dotnet version in global.json, change 'dotnet-version' to the version of the .NET SDK used in your project **** #
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    # **** Please change 'working-directory' to be the location where your .SLN file is located **** #
    - name: Install dependencies
      run: dotnet restore
      working-directory: ./csharp

    # **** Please change the version of Node being used to the one for your project **** #
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    # **** Please update to point to the location where your node dependencies are installed **** #
    - uses: actions/cache@v2
      id: caching-stage
      name: Cache dependencies
      with:
        path: node_modules
        key: ${{ runner.os }}-dependencies-${{ hashfiles('typescript/yarn.lock') }}
        restore-keys: ${{ runner.os }}-dependencies-

    # **** Please update, at least, the working directory below. You may also want to use npm install instead **** #
    - run: yarn
      working-directory: typescript
      if: steps.caching-stage.outputs.cache-hit != 'true'
    
    # **** If you use NPM to install packages, please uncomment this task and delete the yarn task **** #
    # - name: npm install
    #   working-directory: typescript
    #   run: npm install

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - uses: microsoft/RichCodeNavIndexer@v0.1
      with: 
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        languages: csharp,java,typescript,cpp
