### This template is meant to be used by a Java repository running RichNav
### Please fill anything marked above with a "# **** #" comment with the value appropriate for your repository

name: Rich Code Navigation (Java with Maven)

on:
  pull_request:
  push:
  # **** Add any the name of your default branch, or any branch you want indexed on every push **** #
    branches: [ main ]

jobs:
  richnav:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - uses: microsoft/RichCodeNavIndexer@v0.1
      with: 
        languages: java
        repo-token: ${{ secrets.GITHUB_TOKEN }}