### This template is meant to be used by a C# repository running RichNav on a scheduled cadence.
### This is particularly appropriate for reference repositories that aren't updated monthly.
### Please replace the C# specific steps with steps for your particular language
### Please fill anything marked above with a "# **** #" comment with the value appropriate for your repository
name: Rich Code Navigation (.NET Core)

on:
  schedule:
    # **** This runs the action on the 14th of every month at midnight. Adjust the schedule as appropriate for your needs **** #
    - cron: '0 14 * * 1'

jobs:
  build:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v2

    # **** If you've defined a specific dotnet version in global.json, change 'dotnet-version' to the version of the .NET SDK used in your project **** #
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    # **** Please change 'working-directory' to be the location where your .SLN file is located **** #
    - name: Install dependencies
      run: dotnet restore
      working-directory: ./csharp
      
    - uses: microsoft/RichCodeNavIndexer@v0.1
      with: 
        languages: csharp
        repo-token: ${{ secrets.GITHUB_TOKEN }}
